urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import DetailView, ListView
from geogame_core.views import *
from geogame_core.admin_views.admin_views import *
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'geogame.views.home', name='home'),
    # url(r'^geogame/', include('geogame.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
    ('^hello/$', hello),
    ('^index/$', index),
    ('^$', geogame_main),
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout),
    (r'^accounts/profile/$', geogame_main),
    (r'^main/$', main),
    (r'^register/$', register),
    (r'^geogame_main/$', geogame_main),
    (r'^rpc/json_test/$', json_test),
    
    # admin stuff
    
    (r'^rpc/get_game_info/$', get_game_info),
    (r'^rpc/get_active_player_info/$', get_active_player_info),
    (r'^rpc/reset_game/$', reset_game),
    (r'^rpc/change_game_settings/$', change_game_settings),
    (r'^rpc/get_all_settings/$', get_all_settings),
    (r'^rpc/start_game/$', start_game),
    
    # player stuff 
    
    (r'^rpc/get_locations/$', get_locations),
    (r'^rpc/send_message/$', send_message),
    (r'^rpc/take_item/$', take_item),
    (r'^rpc/maintain_activity/$', maintain_activity),
    (r'^rpc/update_client/$', update_client),
    (r'^geogame_admin/$', geogame_admin),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('', (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': 'static'}))

geogame_core/models.py
import datetime as dt

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import simplejson

# hash map/redis store for messages?

NETWORK_TYPES = [('SMALL_WORLD', 'Small world'),]

class AcceptedForm(models.Model):
    
    name = models.CharField(max_length=100)
    content = models.TextField()
    order = models.IntegerField()
    active = models.BooleanField()
    button1_text = models.CharField(max_length=100)
    button2_text = models.CharField(max_length=100)
    

class Item(models.Model):
    
    owner = models.ForeignKey('Player', null=True)
    item_type = models.ForeignKey('ItemType')
    location = models.ForeignKey('Location', null=True)
    
    def __str__(self):
        return '{0!s}'.format(self.item_type.name)
    

class Location(models.Model):

    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=500)
    location_type = models.IntegerField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    
    def __str__(self):
        return '{0!s}'.format(self.name)

class Road(models.Model):
    
    name = models.CharField(max_length=100)
    location1 = models.ForeignKey('Location', related_name='location1')
    location2 = models.ForeignKey('Location', related_name='location2')
    road_points = models.TextField()
    length = models.IntegerField()
    travel_duration = models.IntegerField()
    
    def __str__(self):
        return '{0!s}'.format(self.name)

class Action(models.Model):
    
    action_type = models.CharField(max_length=100)
    player = models.ForeignKey('Player')
    time = models.DateTimeField()
    dest_player = models.ForeignKey('Player', related_name='destination_player', null=True)
    source_location = models.ForeignKey('Location', related_name='source_location', null=True)
    dest_location = models.ForeignKey('Location', related_name='dest_location', null=True)
    item = models.ForeignKey('Item', null=True)
    score_increase = models.IntegerField(null=True)
    new_score = models.IntegerField(null=True)
    location_items = models.CharField(max_length=1000, null=True)
    
class Command(models.Model):
    pass

class Message(models.Model):
    
    time_sent = models.DateField(blank=True)
    sender = models.ForeignKey('Player', blank=True)
    recipient = models.ManyToManyField('Player', related_name='recipient', blank=True)
    content = models.CharField(max_length=1000)
    
    def __str__(self):
        return '{0!s}'.format(self.content)
    

class ItemType(models.Model):
    
    synonyms = models.ManyToManyField('Synonym')
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    replenishable = models.BooleanField()
    icon = models.URLField()
    
    def __str__(self):
        return '{0!s}'.format(self.name)
    

class Synonym(models.Model):
    pass

class Player(models.Model):
    
    user = models.OneToOneField(User)
    
    score = models.IntegerField()
    moving_flag = models.BooleanField()
    neighbors = models.ManyToManyField('self')
    accepted_forms = models.ForeignKey(AcceptedForm)
    
    location = models.ForeignKey(Location, null=True)
    # messages = models.ManyToManyField(Message, null=True)
    # location = None
    
    assigned_item = models.ForeignKey(ItemType, null=True)
    
    admin = models.BooleanField()
    
    status = ''
    last_req = None
    
    def __init__(self, *args, **kwargs):
        super(Player, self).__init__(*args, **kwargs)
        self.last_req = dt.datetime.now()
        self.status = 'active'
    
    def __str__(self):
        return '{0!s}'.format(self.user.username)
        
class Settings(models.Model):
    
    game_duration = models.IntegerField()
    network_type = models.CharField(max_length=100, choices=NETWORK_TYPES)
    graph_density = models.FloatField()
    average_degree = models.FloatField()
    
    rebuild_user_network = models.BooleanField()
    rebuild_road_network = models.BooleanField()
    new_item_assignment = models.BooleanField()
    communication_allowed = models.BooleanField()
    
    min_road_time = models.IntegerField()
    max_road_time = models.IntegerField()
    
    name = models.CharField(max_length=200, unique=True)
    

class Game(models.Model):
    
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(blank=True)
    settings = models.ForeignKey(Settings)
    
    participants = models.ManyToManyField(Player)
    

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Player.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

geogame_core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from models import *
from django import forms

class GameCreationForm(forms.ModelForm):
    
    class Meta:
        model = Game
        exclude = ['participants']
        
class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message
        
class SettingsForm(forms.ModelForm):
    
    class Meta:
        model = Settings

geogame_core/views.py
# import redis
import time
import random
import networkx as nx

from collections import OrderedDict

from threading import Lock, Thread
from Queue import Queue

from django.template.loader import get_template
from django.template import Context, RequestContext
from django.shortcuts import render_to_response
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
from django.utils import simplejson


from models import *
from forms import *
from utils import *

# r_server = redis.Redis('localhost')

active_players = {}
active_players_lock = Lock()

player_network = nx.Graph()
network_initialized = False

messages_queue = SynchronizedMessageQueue()
score_queue = SynchronizedMessageQueue()
command_queue = SynchronizedMessageQueue()

'''
    The command queue is used to propagate information about changes in the world.
    For example, changes in what items are stored in what locations, or perhaps
    changes in road travel times.
    
    ** Command syntax **
    
    A command is a dict that has the following strucutre:
    
    command = {'command': command_name,
                'args': {'arg1': arg1, 'arg2': arg2, ... }}
                
    Args themselves may be arrays or dicts as required
                
    ** Command types **
    
    *** Update location ***
        command_name: 'update_location'
        args: 'id' = location_id
        items: [{'item_type': item.item_type.name, 'id': item.id, 'icon': item.item_type.icon}]
        
    *** Start game (admin) ***
        command_name: 'start_game'
        args: 'duration' = duration
        
'''


def init_player_network():
    ''' A little hack to make it possible to load the player network right from the db
    instead of having to hit "reset" every time
    '''
    
    for name, player in active_players.items():
        for neighbor in player.neighbors.all():
            player_network.add_edges_from([(player, neighbor)])


def monitor_active_users():
    
    interval = dt.timedelta(seconds=5)
    while 1:
        active_players_lock.acquire()
        try:
            for username, player in active_players.items():
                now = dt.datetime.now()
                if player.last_req + interval < now:
                    del active_players[username]
        except Exception as ex:
            print ex
        finally:
            active_players_lock.release()
            
        time.sleep(1)
        
def add_active_user(player):
    active_players_lock.acquire()
    try:
        if player.user.username not in active_players:
            active_players[player.user.username] = player
    except Exception as ex:
        print ex
    finally:
        active_players_lock.release()

def update_active_user(username, score, location):
    
    active_players_lock.acquire()
    try:
        active_players[username].last_req = dt.datetime.now()
        active_players[username].location = location
        active_players[username].score = score
        print username, score, location
    except Exception as ex:
        pass
        # print ex
    finally:
        active_players_lock.release()
        
def get_active_user(player):
    active_players_lock.acquire()
    active_player = None
    try:
        active_player = active_players[player.user.username]
    except Exception as ex:
        # fail silently for now
        pass
        # print 'butts', ex
    finally:
        active_players_lock.release()
        return active_player

monitor_thread = Thread(target=monitor_active_users)
monitor_thread.setDaemon(True)
monitor_thread.start()

@csrf_exempt
def maintain_activity(request):
    if request.user.is_authenticated():
        if request.is_ajax():
            if request.method == 'POST':    
                update_thread = Thread(target=update_active_user, args=(request.user.get_profile(),))
                update_thread.setDaemon(True)
                update_thread.start()
                
                return HttpResponse(simplejson.dumps({'status': 'updated'}), 'application/json')

@csrf_exempt
def update_client(request):
    if request.user.is_authenticated():
        if request.is_ajax():
            if request.method == 'POST':
                data = {}
                player = request.user.get_profile()
                client_score = int(request.POST['player_state[score]']) 
                client_location = Location.objects.get(id=int(request.POST['player_state[location]']))
                print player.user.username, client_score, client_location
                
                cache_player = get_active_user(player)

                # distribute messages
                messages = messages_queue.dequeue_message(player.user.username)
                messages_to_distribute = []
                
                for message in messages:
                    messages_to_distribute.append({'sender': str(message.sender), 'content': str(message.content)})
                    
                data['messages'] = messages_to_distribute
                
                # distribute score
                data ['scores'] = []

                try:
                    scores = score_queue.dequeue_message(player.user.username)
                    scores_to_distribute = []
                    
                    for score in scores:
                        scores_to_distribute.append(score)

                    data['scores'] = scores_to_distribute
                except Exception as ex:
                    print 'sheeeeit', ex
                 
                # update item to find
                
                try:
                    assigned_item = cache_player.assigned_item
                    assigned_item_info = {'item_type': assigned_item.name, 'icon': assigned_item.icon}
                except:
                    assigned_item_info = []
                    
                data['assigned_item'] = assigned_item_info
                
                commands = command_queue.dequeue_message(player.user.username)
                data['commands'] = commands
                
                # update user activity
                update_thread = Thread(target=update_active_user, args=(player.user.username, client_score, client_location))
                update_thread.setDaemon(True)
                update_thread.start()
                
                return HttpResponse(simplejson.dumps(data), 'application/json')

def hello(request):
    return HttpResponse('Hello world! butts')

def index (request):
    t = get_template('index.html')
    html = t.render(Context())
    return render_to_response('index.html', {})

def register (request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/main/")
    else:
        form = UserCreationForm()
    return render_to_response('registration/register.html',
                              {'form': form, 'next': '/main/'},
                              context_instance=RequestContext(request))

def main (request):
    if request.user.is_authenticated():
        return render_to_response('main.html', {}, context_instance=RequestContext(request))
    else:
        return HttpResponse('<font color="red">bad shit happened</font>')

def geogame_main(request):
    user = request.user
    if user is not None:
        if request.user.is_authenticated():
            add_active_user_thread = Thread(target=add_active_user, args=(request.user.get_profile(),))
            add_active_user_thread.setDaemon(True)
            add_active_user_thread.start()
            
            init_player_network();
            print 'network:', player_network.nodes()
            
            return render_to_response('geogame_main.html', {'player': user.get_profile() }, context_instance=RequestContext(request))
        else:
            return HttpResponse("You are not allowed to access this section!")
    else:
        return HttpResponse("User is null")
    
@csrf_exempt
def json_test(request):
    data = {}
    message = "blargh"
    if request.is_ajax():
        if request.method == "GET":
            message = "this is a get request"
        elif request.method == "POST":
            message = "this is a post request"
            # print request.POST
        data = {"look": "at this", "bull": "shit", "message": message}
    else:
        message = "buttts?"
      
    return HttpResponse(simplejson.dumps(data), "application/json")

@csrf_exempt
def get_game_info(request):
    data = {}
    if request.is_ajax():
        if request.method == "POST":
            player = request.user.get_profile();
            cache_player = get_active_user(player)
            data['player_id'] = cache_player.id
            data['player_location'] = cache_player.location.id
            data['player_score'] = cache_player.score
    
    return HttpResponse(simplejson.dumps(data), 'application/json')

@csrf_exempt
def get_locations(request):
    data = []
    if request.is_ajax():
        if request.method == 'POST':
            all_locations = Location.objects.all()
            node_data = [{'id': loc.id, 'name': loc.name, 'lat': loc.latitude, 'lng': loc.longitude,
                          'items': [{'item_type': item.item_type.name, 'id': item.id, 'icon': item.item_type.icon} for item in loc.item_set.all()]} for loc in all_locations]
            all_roads = Road.objects.all()
            link_data = [{'source': road.location1_id, 'target': road.location2_id, 'duration': road.travel_duration} for road in all_roads]
            data = {'nodes': node_data, 'links': link_data}
            #data = {'nodes': [{loc.name: {'lat': loc.latitude, 'lng': loc.longitude} for loc in all_locations}]}

geogame_core/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
  <link rel="stylesheet" href="{{ STATIC_URL }}base.css" type="text/css"/>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block header %}{% endblock %}
  <div class="container">
        {% block content %}{% endblock %}
  </div>
  {% block footer %}{% endblock %}
</body>
</html>

geogame_core/templates/geogame_admin.html
<!DOCTYPE HTML>
<html lang="en">
<head>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/geogame_admin.css" type="text/css"/>
  
  <!-- a bunch of css for menus -->
  <link rel="stylesheet" href="{{ STATIC_URL }}css/menu/helper.css" type="text/css"/>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/menu/dropdown/dropdown.vertical.css" type="text/css"/>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/menu/dropdown/dropdown.linear.css" type="text/css"/>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/menu/dropdown/themes/default/default.linear.css" media="screen" rel="stylesheet" type="text/css" />
  
  <!-- blueprint stuff -->
  <!--<link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/screen.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/print.css" type="text/css" media="print">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/plugins/buttons/screen.css" type="text/css" media="screen">-->
  
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCVTlLbP7-nF5hLUuBVtbosWGoEXMkWo60&sensor=false"></script>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/smoothness/jquery-ui-1.8.23.custom.css" type="text/css">
  
  <!-- data tables-->
  <link rel="stylesheet" href="{{ STATIC_URL }}css/data-tables/jquery.dataTables.css" type="text/css" media="print">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/data-tables/jquery.dataTables_themeroller.css" type="text/css" media="print">
  
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.23.custom.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/fnReloadAjax.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/geogame_admin.js"></script>
  
  <title>GeoGame Admin page</title>
</head>
<body>
	<div class="span-24">
		<ul id="nav" class="dropdown dropdown-linear">
			<li class="dir">Game
				<ul class="dropdown dropdown-linear">
					<li><a href="javascript:void(0);" id="reset-game">Reset game</a></li>
					<li><a href="javascript:void(0);" id="start-game">Start game</a></li>
				</ul>
			</li>
			<li class="dir">Settings
				<ul class="dropdown dropdown-linear">
					<li><a href="javascript:void(0);" id="change-game-settings">Change game settings</a></li>
					<li><a href="/rpc/change_synonyms">Change synonyms</a></li>
					<li><a href="/rpc/change_forms">Change forms</a></li>
				</ul>	
			</li>
			<li class="dir">Commands
				<ul class="dropdown dropdown-linear">
					<li><a href="/rpc/create_user_network">Create user network</a></li>
					<li><a href="/rpc/send_admin_message">Send admin message</a></li>
					<li><a href="/rpc/redraw_user_graph">Redraw user graph</a></li>
					<li><a href="/rpc/show_synonyms">Show synonyms to players</a></li>
				</ul>	
			</li>
		</ul>
	</div>
	<div class="spacer-row">&nbsp;</div>
		<table id="player-table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Location</th>
					<th>Items collected</th>
					<th>Number of neighbors</th>
					<th>Status</th>
					<th>Score</th>
					<th>Goal item</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	
	<!-- define some dialog forms -->
	
	<!-- dialog for a generic message display -->
	
	<div id="message-dialog" class="ui-dialog" title="Attention!">
		
	</div>
	
	<!-- dialog for the reset -->
	 
	<div id="reset-dialog" class="ui-dialog" title="Reset Game">
		<form id="reset-form">
			<fieldset>
				<!--<p>
					<label for="id_start_time">Start time:</label>
					<input type="text" name="start_time" id="id_start_time" />
				</p>
				<p>
					<label for="id_end_time">End time:</label>
					<input type="text" name="end_time" id="id_end_time" />
				</p>-->
				<p>
					<label for="id_settings">Select game settings:</label>
					<select name="settings" id="id_settings">
						<option value="" selected="selected">---------</option>
					</select>
				</p>
			</fieldset>
		</form>
	</div>
	
	<!-- dialog for the settings form -->
	
	<div id="settings-dialog" title="Settings">
		<form id="settings-form">
			<fieldset>
				<p>
					<label for="id_name">Name:</label>
					<input id="id_name" maxlength="200" name="name" type="text"/>
				</p>
				<p>
					<label for="id_game_duration">Game duration:</label>
					<input id="id_game_duration" name="game_duration" type="text"/>
				</p>
				<p>
					<label for="id_network_type">Network type:</label>
					<select id="id_network_type" name="network_type">
						<option value="SMALL_WORLD">Small world</option>
					</select>
					<!--<input id="id_network_type" maxlength="100" name="network_type" type="text"/>-->
				</p>
				<p>
					<label for="id_graph_density">Graph density:</label>
					<input id="id_graph_density" name="graph_density" type="text"/>
				</p>
				<p>
					<label for="id_average_degree">Average degree:</label>
					<input id="id_average_degree" name="average_degree" type="text"/>
				</p>
				<p>
					<label for="id_rebuild_user_network">Rebuild user network:</label>
					<input id="id_rebuild_user_network" name="rebuild_user_network" type="checkbox"/>
				</p>
				<p>
					<label for="id_rebuild_road_network">Rebuild road network:</label>
					<input id="id_rebuild_road_network" name="rebuild_road_network" type="checkbox"/>
				</p>
				<p>
					<label for="id_new_item_assignment">New item assignment:</label>
					<input id="id_new_item_assignment" name="new_item_assignment" type="checkbox"/>
				</p>
				<p>
					<label for="id_communication_allowed">Communication allowed:</label>
					<input id="id_communication_allowed" name="communication_allowed" type="checkbox"/>
				</p>
				<p>
					<label for="id_min_road_time">Min road time:</label>
					<input id="id_min_road_time" name="min_road_time" type="text"/>
				</p>
				<p>
					<label for="id_max_road_time">Max road time:</label>
					<input id="id_max_road_time" name="max_road_time" type="text"/>
				</p>

			</fieldset>
		</form>
	</div>
</body>

geogame_core/templates/geogame_base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/geogame_base.css" type="text/css"/>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCVTlLbP7-nF5hLUuBVtbosWGoEXMkWo60&sensor=false"></script>
  <link rel="stylesheet" href="{{ STATIC_URL }}css/smoothness/jquery-ui-1.8.23.custom.css" type="text/css">
  
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.23.custom.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.jcountdown.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/maplabel.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/markerwithlabel.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/geogame.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/maps.js"></script>
  
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div id="container">
		<div id="header">
			Welcome to the GeoGame {{ player.user.username }}
		</div>
		<div id="locationBar">
			{% block locationBar %}{% endblock %}
		</div>
		<div id="chatBar">
			{% block chatBar %}{% endblock %}
		</div>
		<div id="mapArea">
			{% block mapCanvas %}{% endblock %}
		</div>
		
		<div id="playerBar">
			{% block playerBar %}{% endblock %}
		</div>
	</div>
	
</body>

geogame_core/templates/geogame_main.html
{% extends "geogame_base.html" %}

{% block chatBar %}
	<div id="messageDisplay" style="min-height: 100%">
		&nbsp;
	</div>
	<form id="message_form">
		<textarea id="chatTextArea" rows="10" width="100%">&nbsp;</textarea>
	</form>
	<button id="sendMessage" onclick="send_message();">Send message</button>
{% endblock %}


{% block mapCanvas %}
<div id="map_canvas" style="width:100%; height:100%"></div>
{% endblock %}

{% block playerBar %}
	<div class="player-info"><h3>Item to find: </h3></div>
	<div class="player-info" id="itemImage" style="display: inline-block;"></div>
	<div class="player-info"><h3>Score: </h3></div>
	<div class="player-info" id="scoreBox"></div>
	<div class='player-info' id="timer"><h3>Time remaining:</h3></div>
{% endblock %}

{% block locationBar %}
	<div class="location-info" id="locationLabel"></div>
	<div class="location-info" id="itemContainer"></div>

{% endblock %}

geogame_core/templates/main.html
{% extends "base.html" %}

{% block content %}

<div class="header">
        <h1>welcome to the geogame</h1>
</div>
<div class="sidebar">
        <ul class="sidebar-menu">
                <li>this is one thing</li>
                <li>this is a different thing</li>
        </ul>
</div>

{% endblock %}